In [6]:
import pandas as pd

In [152]:
lms = pd.read_csv("datasets/LMS_Dirty_Dataset.csv")
lms

,student_id,student_name,course,city,age,gender,enrollment_date,course_fee,discount,payment_status,attendance_percent,assignment_score,final_score,rating,mentor,phone,email,completion_status
0,1,Gita,MERN Stack,Kathmandu,17,Female,2026-02-24,10000,10,Pending,73.0,46,98,5,Samriddha,9839323411,user0@gmail.com,Ongoing
1,2,Nabin,Data Science,Itahari,29,Female,2026-06-29,10000,20,Pending,68.0,31,63,3,Manish,9874340113,user1@gmail.com,Completed
2,3,Gita,MERN Stack,Dharan,20,Female,2026-02-20,5000,20,Paid,71.0,31,99,5,Samriddha,9874168652,user2@gmail.com,Completed
3,4,Gita,Digital Marketing,Itahari,20,Female,2026-05-23,7000,0,Pending,88.0,43,38,5,Manish,9864252889,user3@gmail.com,Ongoing
4,5,Gita,Data Science,Itahari,19,Male,2026-05-28,5000,0,Pending,100.0,89,98,5,Ishan,9864166467,user4@gmail.com,Ongoing
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
345,346,Hari,UI/UX,Dharan,21,Female,2026-06-17,10000,20,Paid,98.0,87,56,5,Samriddha,9873827203,user345@gmail.com,Ongoing
346,347,Anisha,Digital Marketing,Biratnagar,31,Female,2026-03-21,5000,10,Paid,45.0,51,44,3,Samriddha,9864328504,user346@gmail.com,Ongoing
347,348,Sita,Flutter,Biratnagar,19,Male,2026-02-05,5000,20,Paid,80.0,89,39,5,Samriddha,9821459197,user347@gmail.com,Completed
348,349,Anisha,UI/UX,Itahari,27,Male,2026-05-05,5000,10,Paid,63.0,58,52,5,Ishan,9862269669,user348@gmail.com,Completed
349,350,Hari,Python with AI/ML,Dharan,19,Female,2026-04-04,5000,20,Pending,84.0,57,62,3,Manish,9803556080,user349@gmail.com,Ongoing

In [8]:
print(lms.head(10))

   student_id student_name             course        city  age  gender  \
0           1         Gita         MERN Stack   Kathmandu   17  Female
1           2        Nabin       Data Science     Itahari   29  Female
2           3         Gita         MERN Stack      Dharan   20  Female
3           4         Gita  Digital Marketing     Itahari   20  Female
4           5         Gita       Data Science     Itahari   19    Male
5           6       Anisha       Data Science      Dharan   18    Male
6           7        Suman         MERN Stack      Dharan   33  Female
7           8         Sita         MERN Stack     Pokhara   28  Female
8           9         Gita            Flutter  Biratnagar   31    Male
9          10         Sita            Flutter      Dharan   25  Female

  enrollment_date  course_fee  discount payment_status  attendance_percent  \
0      2026-02-24       10000        10        Pending                73.0
1      2026-06-29       10000        20        Pending                68.0
2      2026-02-20        5000        20           Paid                71.0
3      2026-05-23        7000         0        Pending                88.0
4      2026-05-28        5000         0        Pending               100.0
5      2026-04-30        7000        10           Paid                57.0
6      2026-05-03        5000         0           Paid                52.0
7      2026-06-23        5000        20        Pending                71.0
8      2026-05-06       -5000        10        Pending                70.0
9      2026-01-15        5000        20        Pending                53.0

   assignment_score  final_score  rating     mentor       phone  \
0                46           98       5  Samriddha  9839323411
1                31           63       3     Manish  9874340113
2                31           99       5  Samriddha  9874168652
3                43           38       5     Manish  9864252889
4                89           98       5      Ishan  9864166467
5                70           70       4  Samriddha  9838336446
6                38           39       4      Ishan  9806614065
7                38           98       5  Samriddha  9879884445
8                88           98       4      Ishan  9869507556
9                88           47       3     Manish  9896293519

             email completion_status
0  user0@gmail.com           Ongoing
1  user1@gmail.com         Completed
2  user2@gmail.com         Completed
3  user3@gmail.com           Ongoing
4  user4@gmail.com           Ongoing
5  user5@gmail.com         Completed
6  user6@gmail.com         Completed
7  user7@gmail.com         Completed
8  user8@gmail.com         Completed
9  user9@gmail.com         Completed

In [10]:
print(lms.tail(10))

     student_id student_name             course        city  age  gender  \
340         341         Hari  Digital Marketing  Biratnagar   31  Female
341         342         Gita            Flutter  Biratnagar   32  Female
342         343        Aarav              UI/UX     Itahari   18    Male
343         344         Gita  Python with AI/ML   Kathmandu   33    Male
344         345         Gita  Digital Marketing     Pokhara   29    Male
345         346         Hari              UI/UX      Dharan   21  Female
346         347       Anisha  Digital Marketing  Biratnagar   31  Female
347         348         Sita            Flutter  Biratnagar   19    Male
348         349       Anisha              UI/UX     Itahari   27    Male
349         350         Hari  Python with AI/ML      Dharan   19  Female

    enrollment_date  course_fee  discount payment_status  attendance_percent  \
340      2026-06-10        5000        20        Pending                96.0
341      2026-04-16        5000        10           Paid                54.0
342      2026-03-01        7000        10           Paid                45.0
343      2026-05-07        5000        20           Paid                67.0
344      2026-05-18       10000        10           Paid                71.0
345      2026-06-17       10000        20           Paid                98.0
346      2026-03-21        5000        10           Paid                45.0
347      2026-02-05        5000        20           Paid                80.0
348      2026-05-05        5000        10           Paid                63.0
349      2026-04-04        5000        20        Pending                84.0

     assignment_score  final_score  rating     mentor       phone  \
340                38           71       5      Ishan  9831430348
341                33           61       5      Ishan  9865928299
342                85           46       5     Manish  9832055006
343                57           30       4  Samriddha  9828498406
344                45           89       4     Manish  9847970014
345                87           56       5  Samriddha  9873827203
346                51           44       3  Samriddha  9864328504
347                89           39       5  Samriddha  9821459197
348                58           52       5      Ishan  9862269669
349                57           62       3     Manish  9803556080

                 email completion_status
340  user340@gmail.com           Ongoing
341  user341@gmail.com           Ongoing
342  user342@gmail.com         Completed
343  user343@gmail.com           Ongoing
344  user344@gmail.com         Completed
345  user345@gmail.com           Ongoing
346  user346@gmail.com           Ongoing
347  user347@gmail.com         Completed
348  user348@gmail.com         Completed
349  user349@gmail.com           Ongoing

In [12]:
print(lms.shape)

(350, 18)

In [16]:
print(lms.columns)

Index(['student_id', 'student_name', 'course', 'city', 'age', 'gender',
       'enrollment_date', 'course_fee', 'discount', 'payment_status',
       'attendance_percent', 'assignment_score', 'final_score', 'rating',
       'mentor', 'phone', 'email', 'completion_status'],
      dtype='str')

In [17]:
print(lms.dtypes)

student_id              int64
student_name              str
course                    str
city                      str
age                     int64
gender                    str
enrollment_date           str
course_fee              int64
discount                int64
payment_status            str
attendance_percent    float64
assignment_score        int64
final_score             int64
rating                  int64
mentor                    str
phone                     str
email                     str
completion_status         str
dtype: object

In [21]:
print(lms.describe())

       student_id         age     course_fee    discount  attendance_percent  \
count  350.000000  350.000000     350.000000  350.000000          349.000000
mean   175.500000   26.174286   10085.711429    9.600000           70.154728
std    101.180532    5.485686   53109.214627    7.929489           16.697929
min      1.000000   17.000000   -5000.000000    0.000000           40.000000
25%     88.250000   21.000000    5000.000000    0.000000           58.000000
50%    175.500000   27.000000    7000.000000   10.000000           70.000000
75%    262.750000   31.000000   10000.000000   20.000000           83.000000
max    350.000000   35.000000  999999.000000   20.000000          100.000000

       assignment_score  final_score      rating
count        350.000000   350.000000  350.000000
mean          67.011429    65.011429    3.960000
std           20.686773    20.556718    0.817852
min           -5.000000    30.000000    3.000000
25%           51.000000    47.000000    3.000000
50%           69.000000    65.000000    4.000000
75%           85.750000    82.000000    5.000000
max          100.000000   100.000000    5.000000

In [134]:
lms.duplicated().sum()
lms.drop_duplicates(inplace = True)
lms

,student_id,student_name,course,city,age,gender,enrollment_date,course_fee,discount,payment_status,attendance_percent,assignment_score,final_score,rating,mentor,phone,email,completion_status
0,1,Gita,MERN Stack,Kathmandu,17,Female,2026-02-24,10000,10,Pending,73.0,46,98,5,Samriddha,9839323411,user0@gmail.com,Ongoing
1,2,Nabin,Data Science,Itahari,29,Female,2026-06-29,10000,20,Pending,68.0,31,63,3,Manish,9874340113,user1@gmail.com,Completed
2,3,Gita,MERN Stack,Dharan,20,Female,2026-02-20,5000,20,Paid,71.0,31,99,5,Samriddha,9874168652,user2@gmail.com,Completed
3,4,Gita,Digital Marketing,Itahari,20,Female,2026-05-23,7000,0,Pending,88.0,43,38,5,Manish,9864252889,user3@gmail.com,Ongoing
4,5,Gita,Data Science,Itahari,19,Male,2026-05-28,5000,0,Pending,100.0,89,98,5,Ishan,9864166467,user4@gmail.com,Ongoing
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
345,346,Hari,UI/UX,Dharan,21,Female,2026-06-17,10000,20,Paid,98.0,87,56,5,Samriddha,9873827203,user345@gmail.com,Ongoing
346,347,Anisha,Digital Marketing,Biratnagar,31,Female,2026-03-21,5000,10,Paid,45.0,51,44,3,Samriddha,9864328504,user346@gmail.com,Ongoing
347,348,Sita,Flutter,Biratnagar,19,Male,2026-02-05,5000,20,Paid,80.0,89,39,5,Samriddha,9821459197,user347@gmail.com,Completed
348,349,Anisha,UI/UX,Itahari,27,Male,2026-05-05,5000,10,Paid,63.0,58,52,5,Ishan,9862269669,user348@gmail.com,Completed
349,350,Hari,Python with AI/ML,Dharan,19,Female,2026-04-04,5000,20,Pending,84.0,57,62,3,Manish,9803556080,user349@gmail.com,Ongoing

In [146]:
lms.isnull().sum()
#print(lms[lms["attendance_percent"].isnull()])
lms["attendance_percent"] = lms["attendance_percent"].fillna(lms["attendance_percent"].median())
lms.head(29)

,student_id,student_name,course,city,age,gender,enrollment_date,course_fee,discount,payment_status,attendance_percent,assignment_score,final_score,rating,mentor,phone,email,completion_status
0,1,Gita,MERN Stack,Kathmandu,17,Female,2026-02-24,10000,10,Pending,73.0,46,98,5,Samriddha,9839323411,user0@gmail.com,Ongoing
1,2,Nabin,Data Science,Itahari,29,Female,2026-06-29,10000,20,Pending,68.0,31,63,3,Manish,9874340113,user1@gmail.com,Completed
2,3,Gita,MERN Stack,Dharan,20,Female,2026-02-20,5000,20,Paid,71.0,31,99,5,Samriddha,9874168652,user2@gmail.com,Completed
3,4,Gita,Digital Marketing,Itahari,20,Female,2026-05-23,7000,0,Pending,88.0,43,38,5,Manish,9864252889,user3@gmail.com,Ongoing
4,5,Gita,Data Science,Itahari,19,Male,2026-05-28,5000,0,Pending,100.0,89,98,5,Ishan,9864166467,user4@gmail.com,Ongoing
5,6,Anisha,Data Science,Dharan,18,Male,2026-04-30,7000,10,Paid,57.0,70,70,4,Samriddha,9838336446,user5@gmail.com,Completed
6,7,Suman,MERN Stack,Dharan,33,Female,2026-05-03,5000,0,Paid,52.0,38,39,4,Ishan,9806614065,user6@gmail.com,Completed
7,8,Sita,MERN Stack,Pokhara,28,Female,2026-06-23,5000,20,Pending,71.0,38,98,5,Samriddha,9879884445,user7@gmail.com,Completed
8,9,Gita,Flutter,Biratnagar,31,Male,2026-05-06,-5000,10,Pending,70.0,88,98,4,Ishan,9869507556,user8@gmail.com,Completed
9,10,Sita,Flutter,Dharan,25,Female,2026-01-15,5000,20,Pending,53.0,88,47,3,Manish,9896293519,user9@gmail.com,Completed
10,11,Hari,Digital Marketing,Kathmandu,29,Female,2026-06-05,10000,20,Paid,79.0,86,44,4,Samriddha,9812877861,user10@gmail.com,Ongoing
11,12,Suman,UI/UX,Biratnagar,31,Male,2026-05-13,10000,10,Paid,52.0,56,32,3,Ishan,9883192950,user11@gmail.com,Ongoing
12,13,Ram,Python with AI/ML,Pokhara,22,Male,2026-01-10,7000,20,Paid,58.0,36,44,4,Manish,9822968599,user12@gmail.com,Completed
13,14,Ram,UI/UX,Biratnagar,33,Male,2026-03-22,10000,0,Pending,91.0,56,43,3,Ishan,9824227697,user13@gmail.com,Completed
14,15,Suman,MERN Stack,Dharan,27,Female,2026-03-23,10000,0,Paid,51.0,40,95,3,Samriddha,9831015358,user14@gmail.com,Completed
15,16,Hari,Digital Marketing,Itahari,17,Female,2026-04-19,5000,20,Pending,98.0,67,41,3,Ishan,9851495815,user15@gmail.com,Ongoing
16,17,Hari,Data Science,Kathmandu,22,Male,2026-06-13,7000,0,Pending,68.0,85,75,4,Ishan,9822375884,user16@gmail.com,Completed
17,18,Gita,Flutter,Kathmandu,23,Female,2026-06-10,10000,10,Pending,50.0,87,47,3,Ishan,9843591398,user17@gmail.com,Completed
18,19,Sita,Flutter,Kathmandu,24,Male,2026-05-09,999999,10,Pending,41.0,75,51,4,Ishan,9803681891,user18@gmail.com,Ongoing
19,20,Ram,MERN Stack,Dharan,26,Male,2026-05-11,5000,0,Pending,92.0,67,71,4,Manish,9805957986,user19@gmail.com,Completed
20,21,Gita,UI/UX,Biratnagar,20,Male,2026-06-23,10000,10,Pending,60.0,58,73,4,Manish,9844634130,user20@gmail.com,Completed
21,22,Nabin,Digital Marketing,Pokhara,19,Female,2026-06-06,10000,0,Pending,77.0,74,50,4,Samriddha,9880644682,user21@gmail.com,Completed
22,23,Aarav,UI/UX,Kathmandu,34,Female,2026-03-06,5000,0,Paid,56.0,48,77,3,Ishan,9882209166,user22@gmail.com,Completed
23,24,Ram,Digital Marketing,Itahari,33,Male,2026-01-23,10000,20,Pending,58.0,30,79,3,Samriddha,9801720253,user23@gmail.com,Completed
24,25,Sita,UI/UX,Biratnagar,27,Male,2026-04-13,5000,10,Pending,86.0,97,37,3,Ishan,9830320015,user24@gmail.com,Ongoing
25,26,Gita,Python with AI/ML,Biratnagar,22,Male,2026-02-22,5000,20,Pending,95.0,38,96,5,Manish,9877015603,user25@gmail.com,Completed
26,27,Ram,Flutter,Pokhara,31,Female,2026-02-25,5000,20,Pending,78.0,85,89,3,Manish,9812961053,user26@gmail.com,Ongoing
27,28,Suman,Python with AI/ML,Pokhara,27,Female,2026-03-02,10000,0,Pending,98.0,51,83,4,Samriddha,9898794165,user27@gmail.com,Ongoing
28,29,Gita,MERN Stack,Biratnagar,29,Male,2026-03-13,7000,10,Pending,70.0,98,80,5,Samriddha,9822305489,user28@gmail.com,Ongoing

In [74]:
lms.dtypes
#print(lms["enrollment_date"])
#lms["enrollment_date"] = pd.to_datetime(lms["enrollment_date"])
#print(lms["enrollment_date"])

student_id                     int64
student_name                     str
course                           str
city                             str
age                            int64
gender                           str
enrollment_date       datetime64[us]
course_fee                     int64
discount                       int64
payment_status                   str
attendance_percent             int64
assignment_score               int64
final_score                    int64
rating                         int64
mentor                           str
phone                            str
email                            str
completion_status                str
dtype: object

In [107]:
lms["city"] = lms["city"].str.strip().str.title()
lms["course"] = lms["course"].str.strip().str.title()
lms["mentor"] = lms["mentor"].str.strip().str.title()
lms["gender"] = lms["gender"].str.strip().str.title()
lms["payment_status"] = lms["payment_status"].str.strip().str.title()
lms["completion_status"] = lms["completion_status"].str.strip().str.title()

In [126]:
lms[lms["age"]<0]
lms[lms["course_fee"]<0]
lms[lms["attendance_percent"]<0]
lms[lms["discount"]<0]
lms[lms["attendance_percent"]<0]
lms[lms["assignment_score"]<0]
lms[lms["final_score"]<0]
lms[lms["rating"]<0]
#lms=lms[lms["course_fee"]>0]

In [163]:
lms[lms["course_fee"]<0]
lms.loc[lms["course_fee"]<0,"course_fee"]=0
lms[lms["assignment_score"]<0]
lms.loc[lms["assignment_score"]<0,"assignment_score"]=0

In [116]:
Q1 = lms["course_fee"].quantile(0.25)
Q3 = lms["course_fee"].quantile(0.75)

IQR = Q3 - Q1

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

outliers = lms[(lms["course_fee"] < lower) | (lms["course_fee"] > upper)]

print(outliers)

    student_id student_name   course        city  age gender enrollment_date  \
8            9         Gita  Flutter  Biratnagar   31   Male      2026-05-06
18          19         Sita  Flutter   Kathmandu   24   Male      2026-05-09

    course_fee  discount payment_status  attendance_percent  assignment_score  \
8        -5000        10        Pending                70.0                88
18      999999        10        Pending                41.0                75

    final_score  rating mentor       phone             email completion_status
8            98       4  Ishan  9869507556   user8@gmail.com         Completed
18           51       4  Ishan  9803681891  user18@gmail.com           Ongoing

    student_id student_name   course        city  age gender enrollment_date  \
8            9         Gita  Flutter  Biratnagar   31   Male      2026-05-06
18          19         Sita  Flutter   Kathmandu   24   Male      2026-05-09

    course_fee  discount payment_status  attendance_percent  assignment_score  \
8        -5000        10        Pending                70.0                88
18      999999        10        Pending                41.0                75

    final_score  rating mentor       phone             email  \
8            98       4  Ishan  9869507556   user8@gmail.com
18           51       4  Ishan  9803681891  user18@gmail.com

   completion_status    Z_score
8          Completed  -0.284051
18           Ongoing  18.639200

In [214]:
Q1 = lms["attendance_percent"].quantile(0.25)
Q3 = lms["attendance_percent"].quantile(0.75)

IQR = Q3 - Q1

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

outliers = lms[(lms["attendance_percent"] < lower) | (lms["attendance_percent"] > upper)]

print(outliers)

Empty DataFrame
Columns: [student_id, student_name, course, city, age, gender, enrollment_date, course_fee, discount, payment_status, attendance_percent, assignment_score, final_score, rating, mentor, phone, email, completion_status]
Index: []

In [89]:
Q1 = lms["assignment_score"].quantile(0.25)
Q3 = lms["assignment_score"].quantile(0.75)
median=lms["assignment_score"].median()
IQR = Q3 - Q1

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

outliers = lms[(lms["assignment_score"] < lower) | (lms["assignment_score"] > upper)]

print(outliers)

    student_id student_name        course     city  age  gender  \
38          39       Anisha  Data Science  Itahari   20  Female

   enrollment_date  course_fee  discount payment_status  attendance_percent  \
38      2026-01-14       10000        10        Pending                70.0

    assignment_score  final_score  rating  mentor       phone  \
38                -5           55       3  Manish  9856058698

               email completion_status   Z_score
38  user38@gmail.com           Ongoing -0.001614

In [34]:
Q1 = lms["final_score"].quantile(0.25)
Q3 = lms["final_score"].quantile(0.75)

IQR = Q3 - Q1

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

outliers = lms[(lms["final_score"] < lower) | (lms["final_score"] > upper)]

print(outliers)

Empty DataFrame
Columns: [student_id, student_name, course, city, age, gender, enrollment_date, course_fee, discount, payment_status, attendance_percent, assignment_score, final_score, rating, mentor, phone, email, completion_status, Z_score]
Index: []

In [109]:
mean = lms["course_fee"].mean()
std = lms["course_fee"].std()
lms["Z_score"] = (lms["course_fee"]-mean)/std
outliers=lms[(lms["Z_score"].abs()>3) |(lms["Z_score"].abs()<-3 )]
outliers

,student_id,student_name,course,city,age,gender,enrollment_date,course_fee,discount,payment_status,attendance_percent,assignment_score,final_score,rating,mentor,phone,email,completion_status,Z_score
18,19,Sita,Flutter,Kathmandu,24,Male,2026-05-09,999999,10,Pending,41.0,75,51,4,Ishan,9803681891,user18@gmail.com,Ongoing,18.6392

In [125]:


lms = lms[(lms["course_fee"] > lower)&(lms["course_fee"] < upper)]

#print(lms_remove)
lms.head(20)

,student_id,student_name,course,city,age,gender,enrollment_date,course_fee,discount,payment_status,attendance_percent,assignment_score,final_score,rating,mentor,phone,email,completion_status
0,1,Gita,MERN Stack,Kathmandu,17,Female,2026-02-24,10000,10,Pending,73.0,46,98,5,Samriddha,9839323411,user0@gmail.com,Ongoing
1,2,Nabin,Data Science,Itahari,29,Female,2026-06-29,10000,20,Pending,68.0,31,63,3,Manish,9874340113,user1@gmail.com,Completed
2,3,Gita,MERN Stack,Dharan,20,Female,2026-02-20,5000,20,Paid,71.0,31,99,5,Samriddha,9874168652,user2@gmail.com,Completed
3,4,Gita,Digital Marketing,Itahari,20,Female,2026-05-23,7000,0,Pending,88.0,43,38,5,Manish,9864252889,user3@gmail.com,Ongoing
4,5,Gita,Data Science,Itahari,19,Male,2026-05-28,5000,0,Pending,100.0,89,98,5,Ishan,9864166467,user4@gmail.com,Ongoing
5,6,Anisha,Data Science,Dharan,18,Male,2026-04-30,7000,10,Paid,57.0,70,70,4,Samriddha,9838336446,user5@gmail.com,Completed
6,7,Suman,MERN Stack,Dharan,33,Female,2026-05-03,5000,0,Paid,52.0,38,39,4,Ishan,9806614065,user6@gmail.com,Completed
7,8,Sita,MERN Stack,Pokhara,28,Female,2026-06-23,5000,20,Pending,71.0,38,98,5,Samriddha,9879884445,user7@gmail.com,Completed
9,10,Sita,Flutter,Dharan,25,Female,2026-01-15,5000,20,Pending,53.0,88,47,3,Manish,9896293519,user9@gmail.com,Completed
10,11,Hari,Digital Marketing,Kathmandu,29,Female,2026-06-05,10000,20,Paid,79.0,86,44,4,Samriddha,9812877861,user10@gmail.com,Ongoing
11,12,Suman,UI/UX,Biratnagar,31,Male,2026-05-13,10000,10,Paid,52.0,56,32,3,Ishan,9883192950,user11@gmail.com,Ongoing
12,13,Ram,Python with AI/ML,Pokhara,22,Male,2026-01-10,7000,20,Paid,58.0,36,44,4,Manish,9822968599,user12@gmail.com,Completed
13,14,Ram,UI/UX,Biratnagar,33,Male,2026-03-22,10000,0,Pending,91.0,56,43,3,Ishan,9824227697,user13@gmail.com,Completed
14,15,Suman,MERN Stack,Dharan,27,Female,2026-03-23,10000,0,Paid,51.0,40,95,3,Samriddha,9831015358,user14@gmail.com,Completed
15,16,Hari,Digital Marketing,Itahari,17,Female,2026-04-19,5000,20,Pending,98.0,67,41,3,Ishan,9851495815,user15@gmail.com,Ongoing
16,17,Hari,Data Science,Kathmandu,22,Male,2026-06-13,7000,0,Pending,68.0,85,75,4,Ishan,9822375884,user16@gmail.com,Completed
17,18,Gita,Flutter,Kathmandu,23,Female,2026-06-10,10000,10,Pending,50.0,87,47,3,Ishan,9843591398,user17@gmail.com,Completed
19,20,Ram,MERN Stack,Dharan,26,Male,2026-05-11,5000,0,Pending,92.0,67,71,4,Manish,9805957986,user19@gmail.com,Completed
20,21,Gita,UI/UX,Biratnagar,20,Male,2026-06-23,10000,10,Pending,60.0,58,73,4,Manish,9844634130,user20@gmail.com,Completed
21,22,Nabin,Digital Marketing,Pokhara,19,Female,2026-06-06,10000,0,Pending,77.0,74,50,4,Samriddha,9880644682,user21@gmail.com,Completed

In [275]:
Q1 = lms["course_fee"].quantile(0.25)
Q3 = lms["course_fee"].quantile(0.75)

IQR = Q3 - Q1

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

median = lms["course_fee"].median()

lms.loc[(lms["course_fee"] < lower) | (lms["course_fee"] > upper),"course_fee"] = median
lms.head(20)

,student_id,student_name,course,city,age,gender,enrollment_date,course_fee,discount,payment_status,attendance_percent,assignment_score,final_score,rating,mentor,phone,email,completion_status
0,1,Gita,MERN Stack,Kathmandu,17,Female,2026-02-24,10000,10,Pending,73.0,46,98,5,Samriddha,9839323411,user0@gmail.com,Ongoing
1,2,Nabin,Data Science,Itahari,29,Female,2026-06-29,10000,20,Pending,68.0,31,63,3,Manish,9874340113,user1@gmail.com,Completed
2,3,Gita,MERN Stack,Dharan,20,Female,2026-02-20,5000,20,Paid,71.0,31,99,5,Samriddha,9874168652,user2@gmail.com,Completed
3,4,Gita,Digital Marketing,Itahari,20,Female,2026-05-23,7000,0,Pending,88.0,43,38,5,Manish,9864252889,user3@gmail.com,Ongoing
4,5,Gita,Data Science,Itahari,19,Male,2026-05-28,5000,0,Pending,100.0,89,98,5,Ishan,9864166467,user4@gmail.com,Ongoing
5,6,Anisha,Data Science,Dharan,18,Male,2026-04-30,7000,10,Paid,57.0,70,70,4,Samriddha,9838336446,user5@gmail.com,Completed
6,7,Suman,MERN Stack,Dharan,33,Female,2026-05-03,5000,0,Paid,52.0,38,39,4,Ishan,9806614065,user6@gmail.com,Completed
7,8,Sita,MERN Stack,Pokhara,28,Female,2026-06-23,5000,20,Pending,71.0,38,98,5,Samriddha,9879884445,user7@gmail.com,Completed
8,9,Gita,Flutter,Biratnagar,31,Male,2026-05-06,7000,10,Pending,70.0,88,98,4,Ishan,9869507556,user8@gmail.com,Completed
9,10,Sita,Flutter,Dharan,25,Female,2026-01-15,5000,20,Pending,53.0,88,47,3,Manish,9896293519,user9@gmail.com,Completed
10,11,Hari,Digital Marketing,Kathmandu,29,Female,2026-06-05,10000,20,Paid,79.0,86,44,4,Samriddha,9812877861,user10@gmail.com,Ongoing
11,12,Suman,UI/UX,Biratnagar,31,Male,2026-05-13,10000,10,Paid,52.0,56,32,3,Ishan,9883192950,user11@gmail.com,Ongoing
12,13,Ram,Python with AI/ML,Pokhara,22,Male,2026-01-10,7000,20,Paid,58.0,36,44,4,Manish,9822968599,user12@gmail.com,Completed
13,14,Ram,UI/UX,Biratnagar,33,Male,2026-03-22,10000,0,Pending,91.0,56,43,3,Ishan,9824227697,user13@gmail.com,Completed
14,15,Suman,MERN Stack,Dharan,27,Female,2026-03-23,10000,0,Paid,51.0,40,95,3,Samriddha,9831015358,user14@gmail.com,Completed
15,16,Hari,Digital Marketing,Itahari,17,Female,2026-04-19,5000,20,Pending,98.0,67,41,3,Ishan,9851495815,user15@gmail.com,Ongoing
16,17,Hari,Data Science,Kathmandu,22,Male,2026-06-13,7000,0,Pending,68.0,85,75,4,Ishan,9822375884,user16@gmail.com,Completed
17,18,Gita,Flutter,Kathmandu,23,Female,2026-06-10,10000,10,Pending,50.0,87,47,3,Ishan,9843591398,user17@gmail.com,Completed
18,19,Sita,Flutter,Kathmandu,24,Male,2026-05-09,7000,10,Pending,41.0,75,51,4,Ishan,9803681891,user18@gmail.com,Ongoing
19,20,Ram,MERN Stack,Dharan,26,Male,2026-05-11,5000,0,Pending,92.0,67,71,4,Manish,9805957986,user19@gmail.com,Completed

In [78]:
Q1 = lms["course_fee"].quantile(0.25)
Q3 = lms["course_fee"].quantile(0.75)

IQR = Q3 - Q1

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

lms["course_fee"] = lms["course_fee"].clip(lower, upper)

lms.head(20)

,student_id,student_name,course,city,age,gender,enrollment_date,course_fee,discount,payment_status,attendance_percent,assignment_score,final_score,rating,mentor,phone,email,completion_status
0,1,Gita,MERN Stack,Kathmandu,17,Female,2026-02-24,10000,10,Pending,73.0,46,98,5,Samriddha,9839323411,user0@gmail.com,Ongoing
1,2,Nabin,Data Science,Itahari,29,Female,2026-06-29,10000,20,Pending,68.0,31,63,3,Manish,9874340113,user1@gmail.com,Completed
2,3,Gita,MERN Stack,Dharan,20,Female,2026-02-20,5000,20,Paid,71.0,31,99,5,Samriddha,9874168652,user2@gmail.com,Completed
3,4,Gita,Digital Marketing,Itahari,20,Female,2026-05-23,7000,0,Pending,88.0,43,38,5,Manish,9864252889,user3@gmail.com,Ongoing
4,5,Gita,Data Science,Itahari,19,Male,2026-05-28,5000,0,Pending,100.0,89,98,5,Ishan,9864166467,user4@gmail.com,Ongoing
5,6,Anisha,Data Science,Dharan,18,Male,2026-04-30,7000,10,Paid,57.0,70,70,4,Samriddha,9838336446,user5@gmail.com,Completed
6,7,Suman,MERN Stack,Dharan,33,Female,2026-05-03,5000,0,Paid,52.0,38,39,4,Ishan,9806614065,user6@gmail.com,Completed
7,8,Sita,MERN Stack,Pokhara,28,Female,2026-06-23,5000,20,Pending,71.0,38,98,5,Samriddha,9879884445,user7@gmail.com,Completed
8,9,Gita,Flutter,Biratnagar,31,Male,2026-05-06,-2500,10,Pending,70.0,88,98,4,Ishan,9869507556,user8@gmail.com,Completed
9,10,Sita,Flutter,Dharan,25,Female,2026-01-15,5000,20,Pending,53.0,88,47,3,Manish,9896293519,user9@gmail.com,Completed
10,11,Hari,Digital Marketing,Kathmandu,29,Female,2026-06-05,10000,20,Paid,79.0,86,44,4,Samriddha,9812877861,user10@gmail.com,Ongoing
11,12,Suman,UI/UX,Biratnagar,31,Male,2026-05-13,10000,10,Paid,52.0,56,32,3,Ishan,9883192950,user11@gmail.com,Ongoing
12,13,Ram,Python with AI/ML,Pokhara,22,Male,2026-01-10,7000,20,Paid,58.0,36,44,4,Manish,9822968599,user12@gmail.com,Completed
13,14,Ram,UI/UX,Biratnagar,33,Male,2026-03-22,10000,0,Pending,91.0,56,43,3,Ishan,9824227697,user13@gmail.com,Completed
14,15,Suman,MERN Stack,Dharan,27,Female,2026-03-23,10000,0,Paid,51.0,40,95,3,Samriddha,9831015358,user14@gmail.com,Completed
15,16,Hari,Digital Marketing,Itahari,17,Female,2026-04-19,5000,20,Pending,98.0,67,41,3,Ishan,9851495815,user15@gmail.com,Ongoing
16,17,Hari,Data Science,Kathmandu,22,Male,2026-06-13,7000,0,Pending,68.0,85,75,4,Ishan,9822375884,user16@gmail.com,Completed
17,18,Gita,Flutter,Kathmandu,23,Female,2026-06-10,10000,10,Pending,50.0,87,47,3,Ishan,9843591398,user17@gmail.com,Completed
18,19,Sita,Flutter,Kathmandu,24,Male,2026-05-09,17500,10,Pending,41.0,75,51,4,Ishan,9803681891,user18@gmail.com,Ongoing
19,20,Ram,MERN Stack,Dharan,26,Male,2026-05-11,5000,0,Pending,92.0,67,71,4,Manish,9805957986,user19@gmail.com,Completed

In [52]:
Q1 = lms["assignment_score"].quantile(0.25)
Q3 = lms["assignment_score"].quantile(0.75)

IQR = Q3 - Q1

lower = Q1 - 1.5 * IQR
lower
upper = Q3 + 1.5 * IQR
lms = lms[(lms["assignment_score"] > lower)&(lms["assignment_score"] < upper)]
lms.head(42)

,student_id,student_name,course,city,age,gender,enrollment_date,course_fee,discount,payment_status,attendance_percent,assignment_score,final_score,rating,mentor,phone,email,completion_status
0,1,Gita,MERN Stack,Kathmandu,17,Female,2026-02-24,10000,10,Pending,73.0,46,98,5,Samriddha,9839323411,user0@gmail.com,Ongoing
1,2,Nabin,Data Science,Itahari,29,Female,2026-06-29,10000,20,Pending,68.0,31,63,3,Manish,9874340113,user1@gmail.com,Completed
2,3,Gita,MERN Stack,Dharan,20,Female,2026-02-20,5000,20,Paid,71.0,31,99,5,Samriddha,9874168652,user2@gmail.com,Completed
3,4,Gita,Digital Marketing,Itahari,20,Female,2026-05-23,7000,0,Pending,88.0,43,38,5,Manish,9864252889,user3@gmail.com,Ongoing
4,5,Gita,Data Science,Itahari,19,Male,2026-05-28,5000,0,Pending,100.0,89,98,5,Ishan,9864166467,user4@gmail.com,Ongoing
5,6,Anisha,Data Science,Dharan,18,Male,2026-04-30,7000,10,Paid,57.0,70,70,4,Samriddha,9838336446,user5@gmail.com,Completed
6,7,Suman,MERN Stack,Dharan,33,Female,2026-05-03,5000,0,Paid,52.0,38,39,4,Ishan,9806614065,user6@gmail.com,Completed
7,8,Sita,MERN Stack,Pokhara,28,Female,2026-06-23,5000,20,Pending,71.0,38,98,5,Samriddha,9879884445,user7@gmail.com,Completed
8,9,Gita,Flutter,Biratnagar,31,Male,2026-05-06,-5000,10,Pending,70.0,88,98,4,Ishan,9869507556,user8@gmail.com,Completed
9,10,Sita,Flutter,Dharan,25,Female,2026-01-15,5000,20,Pending,53.0,88,47,3,Manish,9896293519,user9@gmail.com,Completed
10,11,Hari,Digital Marketing,Kathmandu,29,Female,2026-06-05,10000,20,Paid,79.0,86,44,4,Samriddha,9812877861,user10@gmail.com,Ongoing
11,12,Suman,UI/UX,Biratnagar,31,Male,2026-05-13,10000,10,Paid,52.0,56,32,3,Ishan,9883192950,user11@gmail.com,Ongoing
12,13,Ram,Python with AI/ML,Pokhara,22,Male,2026-01-10,7000,20,Paid,58.0,36,44,4,Manish,9822968599,user12@gmail.com,Completed
13,14,Ram,UI/UX,Biratnagar,33,Male,2026-03-22,10000,0,Pending,91.0,56,43,3,Ishan,9824227697,user13@gmail.com,Completed
14,15,Suman,MERN Stack,Dharan,27,Female,2026-03-23,10000,0,Paid,51.0,40,95,3,Samriddha,9831015358,user14@gmail.com,Completed
15,16,Hari,Digital Marketing,Itahari,17,Female,2026-04-19,5000,20,Pending,98.0,67,41,3,Ishan,9851495815,user15@gmail.com,Ongoing
16,17,Hari,Data Science,Kathmandu,22,Male,2026-06-13,7000,0,Pending,68.0,85,75,4,Ishan,9822375884,user16@gmail.com,Completed
17,18,Gita,Flutter,Kathmandu,23,Female,2026-06-10,10000,10,Pending,50.0,87,47,3,Ishan,9843591398,user17@gmail.com,Completed
18,19,Sita,Flutter,Kathmandu,24,Male,2026-05-09,999999,10,Pending,41.0,75,51,4,Ishan,9803681891,user18@gmail.com,Ongoing
19,20,Ram,MERN Stack,Dharan,26,Male,2026-05-11,5000,0,Pending,92.0,67,71,4,Manish,9805957986,user19@gmail.com,Completed
20,21,Gita,UI/UX,Biratnagar,20,Male,2026-06-23,10000,10,Pending,60.0,58,73,4,Manish,9844634130,user20@gmail.com,Completed
21,22,Nabin,Digital Marketing,Pokhara,19,Female,2026-06-06,10000,0,Pending,77.0,74,50,4,Samriddha,9880644682,user21@gmail.com,Completed
22,23,Aarav,UI/UX,Kathmandu,34,Female,2026-03-06,5000,0,Paid,56.0,48,77,3,Ishan,9882209166,user22@gmail.com,Completed
23,24,Ram,Digital Marketing,Itahari,33,Male,2026-01-23,10000,20,Pending,58.0,30,79,3,Samriddha,9801720253,user23@gmail.com,Completed
24,25,Sita,UI/UX,Biratnagar,27,Male,2026-04-13,5000,10,Pending,86.0,97,37,3,Ishan,9830320015,user24@gmail.com,Ongoing
25,26,Gita,Python with AI/ML,Biratnagar,22,Male,2026-02-22,5000,20,Pending,95.0,38,96,5,Manish,9877015603,user25@gmail.com,Completed
26,27,Ram,Flutter,Pokhara,31,Female,2026-02-25,5000,20,Pending,78.0,85,89,3,Manish,9812961053,user26@gmail.com,Ongoing
27,28,Suman,Python with AI/ML,Pokhara,27,Female,2026-03-02,10000,0,Pending,98.0,51,83,4,Samriddha,9898794165,user27@gmail.com,Ongoing
28,29,Gita,MERN Stack,Biratnagar,29,Male,2026-03-13,7000,10,Pending,NaN,98,80,5,Samriddha,9822305489,user28@gmail.com,Ongoing
29,30,Anisha,Flutter,Dharan,30,Male,2026-02-19,7000,20,Paid,64.0,99,83,4,Manish,9856441656,user29@gmail.com,Ongoing
30,31,Hari,MERN Stack,Pokhara,19,Male,2026-06-22,10000,0,Paid,83.0,55,47,3,Ishan,9893662023,user30@gmail.com,Completed
31,32,Suman,Data Science,Kathmandu,19,Female,2026-05-27,10000,20,Pending,62.0,35,53,5,Samriddha,9834450458,user31@gmail.com,Completed
32,33,Nabin,Digital Marketing,Biratnagar,24,Female,2026-04-04,7000,20,Pending,64.0,79,47,4,Manish,9847055580,user32@gmail.com,Ongoing
33,34,Anisha,Flutter,Itahari,20,Female,2026-06-29,7000,20,Paid,41.0,95,30,3,Ishan,9844429529,user33@gmail.com,Ongoing
34,35,Suman,Data Science,Kathmandu,32,Female,2026-06-03,5000,0,Paid,48.0,72,88,4,Manish,9831049943,user34@gmail.com,Completed
35,36,Gita,UI/UX,Pokhara,30,Female,2026-04-02,10000,0,Paid,94.0,79,44,3,Samriddha,9871287641,user35@gmail.com,Completed
36,37,Sita,Flutter,Dharan,34,Male,2026-02-13,5000,20,Paid,59.0,39,80,5,Samriddha,9858060838,user36@gmail.com,Ongoing
37,38,Gita,Python with AI/ML,Itahari,27,Male,2026-01-20,10000,0,Pending,45.0,77,99,3,Samriddha,9807570173,user37@gmail.com,Completed
39,40,Suman,MERN Stack,Pokhara,22,Female,2026-03-13,7000,10,Pending,58.0,30,71,3,Manish,9885371171,user39@gmail.com,Ongoing
40,41,Aarav,Python with AI/ML,Kathmandu,29,Female,2026-05-10,7000,0,Pending,78.0,43,63,5,Ishan,9851841157,user40@gmail.com,Completed
41,42,Nabin,MERN Stack,Kathmandu,25,Male,2026-06-08,5000,10,Pending,43.0,60,73,3,Ishan,9864779360,user41@gmail.com,Completed
42,43,Suman,Python with AI/ML,Itahari,27,Female,2026-05-22,5000,10,Pending,43.0,81,66,4,Samriddha,9876961281,user42@gmail.com,Ongoing

In [58]:
Q1 = lms["assignment_score"].quantile(0.25)
Q3 = lms["assignment_score"].quantile(0.75)

IQR = Q3 - Q1

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

median = lms["assignment_score"].median()

lms.loc[(lms["assignment_score"] < lower) | (lms["assignment_score"] > upper),"assignment_score"] = median
lms.head(40)

,student_id,student_name,course,city,age,gender,enrollment_date,course_fee,discount,payment_status,attendance_percent,assignment_score,final_score,rating,mentor,phone,email,completion_status
0,1,Gita,MERN Stack,Kathmandu,17,Female,2026-02-24,10000,10,Pending,73.0,46,98,5,Samriddha,9839323411,user0@gmail.com,Ongoing
1,2,Nabin,Data Science,Itahari,29,Female,2026-06-29,10000,20,Pending,68.0,31,63,3,Manish,9874340113,user1@gmail.com,Completed
2,3,Gita,MERN Stack,Dharan,20,Female,2026-02-20,5000,20,Paid,71.0,31,99,5,Samriddha,9874168652,user2@gmail.com,Completed
3,4,Gita,Digital Marketing,Itahari,20,Female,2026-05-23,7000,0,Pending,88.0,43,38,5,Manish,9864252889,user3@gmail.com,Ongoing
4,5,Gita,Data Science,Itahari,19,Male,2026-05-28,5000,0,Pending,100.0,89,98,5,Ishan,9864166467,user4@gmail.com,Ongoing
5,6,Anisha,Data Science,Dharan,18,Male,2026-04-30,7000,10,Paid,57.0,70,70,4,Samriddha,9838336446,user5@gmail.com,Completed
6,7,Suman,MERN Stack,Dharan,33,Female,2026-05-03,5000,0,Paid,52.0,38,39,4,Ishan,9806614065,user6@gmail.com,Completed
7,8,Sita,MERN Stack,Pokhara,28,Female,2026-06-23,5000,20,Pending,71.0,38,98,5,Samriddha,9879884445,user7@gmail.com,Completed
8,9,Gita,Flutter,Biratnagar,31,Male,2026-05-06,-5000,10,Pending,70.0,88,98,4,Ishan,9869507556,user8@gmail.com,Completed
9,10,Sita,Flutter,Dharan,25,Female,2026-01-15,5000,20,Pending,53.0,88,47,3,Manish,9896293519,user9@gmail.com,Completed
10,11,Hari,Digital Marketing,Kathmandu,29,Female,2026-06-05,10000,20,Paid,79.0,86,44,4,Samriddha,9812877861,user10@gmail.com,Ongoing
11,12,Suman,UI/UX,Biratnagar,31,Male,2026-05-13,10000,10,Paid,52.0,56,32,3,Ishan,9883192950,user11@gmail.com,Ongoing
12,13,Ram,Python with AI/ML,Pokhara,22,Male,2026-01-10,7000,20,Paid,58.0,36,44,4,Manish,9822968599,user12@gmail.com,Completed
13,14,Ram,UI/UX,Biratnagar,33,Male,2026-03-22,10000,0,Pending,91.0,56,43,3,Ishan,9824227697,user13@gmail.com,Completed
14,15,Suman,MERN Stack,Dharan,27,Female,2026-03-23,10000,0,Paid,51.0,40,95,3,Samriddha,9831015358,user14@gmail.com,Completed
15,16,Hari,Digital Marketing,Itahari,17,Female,2026-04-19,5000,20,Pending,98.0,67,41,3,Ishan,9851495815,user15@gmail.com,Ongoing
16,17,Hari,Data Science,Kathmandu,22,Male,2026-06-13,7000,0,Pending,68.0,85,75,4,Ishan,9822375884,user16@gmail.com,Completed
17,18,Gita,Flutter,Kathmandu,23,Female,2026-06-10,10000,10,Pending,50.0,87,47,3,Ishan,9843591398,user17@gmail.com,Completed
18,19,Sita,Flutter,Kathmandu,24,Male,2026-05-09,999999,10,Pending,41.0,75,51,4,Ishan,9803681891,user18@gmail.com,Ongoing
19,20,Ram,MERN Stack,Dharan,26,Male,2026-05-11,5000,0,Pending,92.0,67,71,4,Manish,9805957986,user19@gmail.com,Completed
20,21,Gita,UI/UX,Biratnagar,20,Male,2026-06-23,10000,10,Pending,60.0,58,73,4,Manish,9844634130,user20@gmail.com,Completed
21,22,Nabin,Digital Marketing,Pokhara,19,Female,2026-06-06,10000,0,Pending,77.0,74,50,4,Samriddha,9880644682,user21@gmail.com,Completed
22,23,Aarav,UI/UX,Kathmandu,34,Female,2026-03-06,5000,0,Paid,56.0,48,77,3,Ishan,9882209166,user22@gmail.com,Completed
23,24,Ram,Digital Marketing,Itahari,33,Male,2026-01-23,10000,20,Pending,58.0,30,79,3,Samriddha,9801720253,user23@gmail.com,Completed
24,25,Sita,UI/UX,Biratnagar,27,Male,2026-04-13,5000,10,Pending,86.0,97,37,3,Ishan,9830320015,user24@gmail.com,Ongoing
25,26,Gita,Python with AI/ML,Biratnagar,22,Male,2026-02-22,5000,20,Pending,95.0,38,96,5,Manish,9877015603,user25@gmail.com,Completed
26,27,Ram,Flutter,Pokhara,31,Female,2026-02-25,5000,20,Pending,78.0,85,89,3,Manish,9812961053,user26@gmail.com,Ongoing
27,28,Suman,Python with AI/ML,Pokhara,27,Female,2026-03-02,10000,0,Pending,98.0,51,83,4,Samriddha,9898794165,user27@gmail.com,Ongoing
28,29,Gita,MERN Stack,Biratnagar,29,Male,2026-03-13,7000,10,Pending,NaN,98,80,5,Samriddha,9822305489,user28@gmail.com,Ongoing
29,30,Anisha,Flutter,Dharan,30,Male,2026-02-19,7000,20,Paid,64.0,99,83,4,Manish,9856441656,user29@gmail.com,Ongoing
30,31,Hari,MERN Stack,Pokhara,19,Male,2026-06-22,10000,0,Paid,83.0,55,47,3,Ishan,9893662023,user30@gmail.com,Completed
31,32,Suman,Data Science,Kathmandu,19,Female,2026-05-27,10000,20,Pending,62.0,35,53,5,Samriddha,9834450458,user31@gmail.com,Completed
32,33,Nabin,Digital Marketing,Biratnagar,24,Female,2026-04-04,7000,20,Pending,64.0,79,47,4,Manish,9847055580,user32@gmail.com,Ongoing
33,34,Anisha,Flutter,Itahari,20,Female,2026-06-29,7000,20,Paid,41.0,95,30,3,Ishan,9844429529,user33@gmail.com,Ongoing
34,35,Suman,Data Science,Kathmandu,32,Female,2026-06-03,5000,0,Paid,48.0,72,88,4,Manish,9831049943,user34@gmail.com,Completed
35,36,Gita,UI/UX,Pokhara,30,Female,2026-04-02,10000,0,Paid,94.0,79,44,3,Samriddha,9871287641,user35@gmail.com,Completed
36,37,Sita,Flutter,Dharan,34,Male,2026-02-13,5000,20,Paid,59.0,39,80,5,Samriddha,9858060838,user36@gmail.com,Ongoing
37,38,Gita,Python with AI/ML,Itahari,27,Male,2026-01-20,10000,0,Pending,45.0,77,99,3,Samriddha,9807570173,user37@gmail.com,Completed
38,39,Anisha,Data Science,Itahari,20,Female,2026-01-14,10000,10,Pending,70.0,69,55,3,Manish,9856058698,user38@gmail.com,Ongoing
39,40,Suman,MERN Stack,Pokhara,22,Female,2026-03-13,7000,10,Pending,58.0,30,71,3,Manish,9885371171,user39@gmail.com,Ongoing

In [62]:
Q1 = lms["assignment_score"].quantile(0.25)
Q3 = lms["assignment_score"].quantile(0.75)

IQR = Q3 - Q1

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

lms["assignment_score"] = lms["assignment_score"].clip(lower, upper)

lms.head(40)

,student_id,student_name,course,city,age,gender,enrollment_date,course_fee,discount,payment_status,attendance_percent,assignment_score,final_score,rating,mentor,phone,email,completion_status
0,1,Gita,MERN Stack,Kathmandu,17,Female,2026-02-24,10000,10,Pending,73.0,46.000,98,5,Samriddha,9839323411,user0@gmail.com,Ongoing
1,2,Nabin,Data Science,Itahari,29,Female,2026-06-29,10000,20,Pending,68.0,31.000,63,3,Manish,9874340113,user1@gmail.com,Completed
2,3,Gita,MERN Stack,Dharan,20,Female,2026-02-20,5000,20,Paid,71.0,31.000,99,5,Samriddha,9874168652,user2@gmail.com,Completed
3,4,Gita,Digital Marketing,Itahari,20,Female,2026-05-23,7000,0,Pending,88.0,43.000,38,5,Manish,9864252889,user3@gmail.com,Ongoing
4,5,Gita,Data Science,Itahari,19,Male,2026-05-28,5000,0,Pending,100.0,89.000,98,5,Ishan,9864166467,user4@gmail.com,Ongoing
5,6,Anisha,Data Science,Dharan,18,Male,2026-04-30,7000,10,Paid,57.0,70.000,70,4,Samriddha,9838336446,user5@gmail.com,Completed
6,7,Suman,MERN Stack,Dharan,33,Female,2026-05-03,5000,0,Paid,52.0,38.000,39,4,Ishan,9806614065,user6@gmail.com,Completed
7,8,Sita,MERN Stack,Pokhara,28,Female,2026-06-23,5000,20,Pending,71.0,38.000,98,5,Samriddha,9879884445,user7@gmail.com,Completed
8,9,Gita,Flutter,Biratnagar,31,Male,2026-05-06,-5000,10,Pending,70.0,88.000,98,4,Ishan,9869507556,user8@gmail.com,Completed
9,10,Sita,Flutter,Dharan,25,Female,2026-01-15,5000,20,Pending,53.0,88.000,47,3,Manish,9896293519,user9@gmail.com,Completed
10,11,Hari,Digital Marketing,Kathmandu,29,Female,2026-06-05,10000,20,Paid,79.0,86.000,44,4,Samriddha,9812877861,user10@gmail.com,Ongoing
11,12,Suman,UI/UX,Biratnagar,31,Male,2026-05-13,10000,10,Paid,52.0,56.000,32,3,Ishan,9883192950,user11@gmail.com,Ongoing
12,13,Ram,Python with AI/ML,Pokhara,22,Male,2026-01-10,7000,20,Paid,58.0,36.000,44,4,Manish,9822968599,user12@gmail.com,Completed
13,14,Ram,UI/UX,Biratnagar,33,Male,2026-03-22,10000,0,Pending,91.0,56.000,43,3,Ishan,9824227697,user13@gmail.com,Completed
14,15,Suman,MERN Stack,Dharan,27,Female,2026-03-23,10000,0,Paid,51.0,40.000,95,3,Samriddha,9831015358,user14@gmail.com,Completed
15,16,Hari,Digital Marketing,Itahari,17,Female,2026-04-19,5000,20,Pending,98.0,67.000,41,3,Ishan,9851495815,user15@gmail.com,Ongoing
16,17,Hari,Data Science,Kathmandu,22,Male,2026-06-13,7000,0,Pending,68.0,85.000,75,4,Ishan,9822375884,user16@gmail.com,Completed
17,18,Gita,Flutter,Kathmandu,23,Female,2026-06-10,10000,10,Pending,50.0,87.000,47,3,Ishan,9843591398,user17@gmail.com,Completed
18,19,Sita,Flutter,Kathmandu,24,Male,2026-05-09,999999,10,Pending,41.0,75.000,51,4,Ishan,9803681891,user18@gmail.com,Ongoing
19,20,Ram,MERN Stack,Dharan,26,Male,2026-05-11,5000,0,Pending,92.0,67.000,71,4,Manish,9805957986,user19@gmail.com,Completed
20,21,Gita,UI/UX,Biratnagar,20,Male,2026-06-23,10000,10,Pending,60.0,58.000,73,4,Manish,9844634130,user20@gmail.com,Completed
21,22,Nabin,Digital Marketing,Pokhara,19,Female,2026-06-06,10000,0,Pending,77.0,74.000,50,4,Samriddha,9880644682,user21@gmail.com,Completed
22,23,Aarav,UI/UX,Kathmandu,34,Female,2026-03-06,5000,0,Paid,56.0,48.000,77,3,Ishan,9882209166,user22@gmail.com,Completed
23,24,Ram,Digital Marketing,Itahari,33,Male,2026-01-23,10000,20,Pending,58.0,30.000,79,3,Samriddha,9801720253,user23@gmail.com,Completed
24,25,Sita,UI/UX,Biratnagar,27,Male,2026-04-13,5000,10,Pending,86.0,97.000,37,3,Ishan,9830320015,user24@gmail.com,Ongoing
25,26,Gita,Python with AI/ML,Biratnagar,22,Male,2026-02-22,5000,20,Pending,95.0,38.000,96,5,Manish,9877015603,user25@gmail.com,Completed
26,27,Ram,Flutter,Pokhara,31,Female,2026-02-25,5000,20,Pending,78.0,85.000,89,3,Manish,9812961053,user26@gmail.com,Ongoing
27,28,Suman,Python with AI/ML,Pokhara,27,Female,2026-03-02,10000,0,Pending,98.0,51.000,83,4,Samriddha,9898794165,user27@gmail.com,Ongoing
28,29,Gita,MERN Stack,Biratnagar,29,Male,2026-03-13,7000,10,Pending,NaN,98.000,80,5,Samriddha,9822305489,user28@gmail.com,Ongoing
29,30,Anisha,Flutter,Dharan,30,Male,2026-02-19,7000,20,Paid,64.0,99.000,83,4,Manish,9856441656,user29@gmail.com,Ongoing
30,31,Hari,MERN Stack,Pokhara,19,Male,2026-06-22,10000,0,Paid,83.0,55.000,47,3,Ishan,9893662023,user30@gmail.com,Completed
31,32,Suman,Data Science,Kathmandu,19,Female,2026-05-27,10000,20,Pending,62.0,35.000,53,5,Samriddha,9834450458,user31@gmail.com,Completed
32,33,Nabin,Digital Marketing,Biratnagar,24,Female,2026-04-04,7000,20,Pending,64.0,79.000,47,4,Manish,9847055580,user32@gmail.com,Ongoing
33,34,Anisha,Flutter,Itahari,20,Female,2026-06-29,7000,20,Paid,41.0,95.000,30,3,Ishan,9844429529,user33@gmail.com,Ongoing
34,35,Suman,Data Science,Kathmandu,32,Female,2026-06-03,5000,0,Paid,48.0,72.000,88,4,Manish,9831049943,user34@gmail.com,Completed
35,36,Gita,UI/UX,Pokhara,30,Female,2026-04-02,10000,0,Paid,94.0,79.000,44,3,Samriddha,9871287641,user35@gmail.com,Completed
36,37,Sita,Flutter,Dharan,34,Male,2026-02-13,5000,20,Paid,59.0,39.000,80,5,Samriddha,9858060838,user36@gmail.com,Ongoing
37,38,Gita,Python with AI/ML,Itahari,27,Male,2026-01-20,10000,0,Pending,45.0,77.000,99,3,Samriddha,9807570173,user37@gmail.com,Completed
38,39,Anisha,Data Science,Itahari,20,Female,2026-01-14,10000,10,Pending,70.0,-1.125,55,3,Manish,9856058698,user38@gmail.com,Ongoing
39,40,Suman,MERN Stack,Pokhara,22,Female,2026-03-13,7000,10,Pending,58.0,30.000,71,3,Manish,9885371171,user39@gmail.com,Ongoing

In [96]:
mean = lms["course_fee"].mean()
std = lms["course_fee"].std()
lms["Z_score"] = (lms["course_fee"]-mean)/std
outliers=lms[(lms["Z_score"].abs()>3) |(lms["Z_score"].abs()<-3 )]
outliers

,student_id,student_name,course,city,age,gender,enrollment_date,course_fee,discount,payment_status,attendance_percent,assignment_score,final_score,rating,mentor,phone,email,completion_status,Z_score
18,19,Sita,Flutter,Kathmandu,24,Male,2026-05-09,999999,10,Pending,41.0,75,51,4,Ishan,9803681891,user18@gmail.com,Ongoing,18.6392

In [66]:
mean = lms["attendance_percent"].mean()
std = lms["attendance_percent"].std()
lms["Z_score"] = (lms["attendance_percent"]-mean)/std
outliers=lms[(lms["Z_score"].abs()>3) |(lms["Z_score"].abs()<-3 )]
outliers

Empty DataFrame
Columns: [student_id, student_name, course, city, age, gender, enrollment_date, course_fee, discount, payment_status, attendance_percent, assignment_score, final_score, rating, mentor, phone, email, completion_status, Z_score]
Index: []

In [26]:
mean = lms["assignment_score"].mean()
std = lms["assignment_score"].std()
lms["Z_score"] = (lms["assignment_score"]-mean)/std
outliers=lms[(lms["Z_score"].abs()>3) |(lms["Z_score"].abs()<-3 )]
outliers

,student_id,student_name,course,city,age,gender,enrollment_date,course_fee,discount,payment_status,attendance_percent,assignment_score,final_score,rating,mentor,phone,email,completion_status,Z_score
38,39,Anisha,Data Science,Itahari,20,Female,2026-01-14,10000,10,Pending,70.0,-5,55,3,Manish,9856058698,user38@gmail.com,Ongoing,-3.481037

In [27]:
mean = lms["final_score"].mean()
std = lms["final_score"].std()
lms["Z_score"] = (lms["final_score"]-mean)/std
outliers=lms[(lms["Z_score"].abs()>3) |(lms["Z_score"].abs()<-3 )]
outliers

Empty DataFrame
Columns: [student_id, student_name, course, city, age, gender, enrollment_date, course_fee, discount, payment_status, attendance_percent, assignment_score, final_score, rating, mentor, phone, email, completion_status, Z_score]
Index: []